# Generated by Django 5.0.6 on 2024-06-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('phonenumber', models.IntegerField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('linkedId', models.IntegerField(null=True)),
                ('linkPrecedence', models.CharField(default='primary', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
            ],
        ),
    ]
