# Generated by Django 5.0.6 on 2024-06-03 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdentityAPP', '0002_alter_contactmodel_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 15, 49, 46, 623716, tzinfo=datetime.timezone.utc)),
        ),
    ]
