# Generated by Django 5.0.6 on 2024-06-03 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdentityAPP', '0003_alter_contactmodel_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 18, 35, 14, 625294, tzinfo=datetime.timezone.utc)),
        ),
    ]
