# Generated by Django 5.0.6 on 2024-06-03 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdentityAPP', '0004_alter_contactmodel_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 18, 59, 49, 720490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phonenumber',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
